# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/caesar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import requests
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "../platforms"


class Ui_call_api_decrypt_2(object):
    def setupUi(self, call_api_decrypt_2):
        call_api_decrypt_2.setObjectName("call_api_decrypt_2")
        call_api_decrypt_2.resize(800, 600)

        self.centralwidget = QtWidgets.QWidget(call_api_decrypt_2)
        self.centralwidget.setObjectName("centralwidget")

        # Main vertical layout
        self.main_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.main_layout.setContentsMargins(30, 20, 30, 20)
        self.main_layout.setSpacing(16)

        # Title
        self.label = QtWidgets.QLabel()
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(26)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.main_layout.addWidget(self.label)

        # Form area
        form_widget = QtWidgets.QWidget()
        form_layout = QtWidgets.QFormLayout(form_widget)
        form_layout.setLabelAlignment(QtCore.Qt.AlignRight)
        form_layout.setFormAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        form_layout.setHorizontalSpacing(12)

        # Plain text
        self.textEdit = QtWidgets.QTextEdit()
        self.textEdit.setObjectName("textEdit")
        self.textEdit.setPlaceholderText("Enter plain text here...")
        self.textEdit.setMinimumHeight(80)
        form_layout.addRow("Plain Text:", self.textEdit)

        # Key
        self.textEdit_2 = QtWidgets.QTextEdit()
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_2.setPlaceholderText("Shift key (e.g. 3)")
        self.textEdit_2.setMaximumHeight(35)
        form_layout.addRow("Key:", self.textEdit_2)

        # Cipher text
        self.textEdit_3 = QtWidgets.QTextEdit()
        self.textEdit_3.setReadOnly(True)  # Đảm bảo ô này chỉ để xuất kết quả
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_3.setPlaceholderText("Cipher text will appear here...")
        self.textEdit_3.setMinimumHeight(80)
        form_layout.addRow("Cipher Text:", self.textEdit_3)

        self.main_layout.addWidget(form_widget)

        # Buttons
        btn_widget = QtWidgets.QWidget()
        btn_layout = QtWidgets.QHBoxLayout(btn_widget)
        btn_layout.addStretch()
        self.call_api_encrypt = QtWidgets.QPushButton("Encrypt")
        self.call_api_encrypt.setObjectName("call_api_encrypt")
        self.call_api_decrypt = QtWidgets.QPushButton("Decrypt")
        self.call_api_decrypt.setObjectName("call_api_decrypt")
        btn_layout.addWidget(self.call_api_encrypt)
        btn_layout.addSpacing(20)
        btn_layout.addWidget(self.call_api_decrypt)
        btn_layout.addStretch()

        self.main_layout.addWidget(btn_widget)

        call_api_decrypt_2.setCentralWidget(self.centralwidget)

        # Status bar and menubar (default)
        self.menubar = QtWidgets.QMenuBar(call_api_decrypt_2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        call_api_decrypt_2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(call_api_decrypt_2)
        call_api_decrypt_2.setStatusBar(self.statusbar)

        self.retranslateUi(call_api_decrypt_2)
        QtCore.QMetaObject.connectSlotsByName(call_api_decrypt_2)

        # Kết nối các nút bấm với logic xử lý API trực tiếp trong file này
        self.call_api_encrypt.clicked.connect(self.encrypt_logic)
        self.call_api_decrypt.clicked.connect(self.decrypt_logic)

    def encrypt_logic(self):
        url = "http://127.0.0.1:5000/api/caesar/encrypt"
        payload = {
            "plain_text": self.textEdit.toPlainText(),
            "key": self.textEdit_2.toPlainText().strip()
        }
        try:
            # Gọi API tới server Flask
            response = requests.post(url, json=payload)
            if response.status_code == 200:
                data = response.json()
                # Lấy kết quả từ API (tương thích cả Lab 02 và Lab 03)
                result = data.get("encrypted_message") or data.get("encrypted_text", "")
                # Xuất kết quả ra ô Cipher Text
                self.textEdit_3.setText(result)
                QMessageBox.information(None, "Thông báo", "Mã hóa thành công!")
            else:
                QMessageBox.warning(None, "Lỗi", "Không thể mã hóa. Kiểm tra lại Key (phải là số).")
        except Exception as e:
            QMessageBox.critical(None, "Lỗi kết nối", f"Hãy chắc chắn rằng api.py đang chạy!\n{e}")

    def decrypt_logic(self):
        url = "http://127.0.0.1:5000/api/caesar/decrypt"
        # Khi giải mã, lấy dữ liệu từ ô Cipher Text (đang ReadOnly) để gửi đi
        payload = {
            "cipher_text": self.textEdit_3.toPlainText(),
            "key": self.textEdit_2.toPlainText().strip()
        }
        try:
            response = requests.post(url, json=payload)
            if response.status_code == 200:
                data = response.json()
                # Lấy kết quả giải mã
                result = data.get("decrypted_message") or data.get("decrypted_text", "")
                # Trả kết quả về ô Plain Text
                self.textEdit.setText(result)
                QMessageBox.information(None, "Thông báo", "Giải mã thành công!")
            else:
                QMessageBox.warning(None, "Lỗi", "Không thể giải mã. Kiểm tra lại dữ liệu và Key.")
        except Exception as e:
            QMessageBox.critical(None, "Lỗi kết nối", f"Hãy chắc chắn rằng api.py đang chạy!\n{e}")

    def retranslateUi(self, call_api_decrypt_2):
        _translate = QtCore.QCoreApplication.translate
        call_api_decrypt_2.setWindowTitle(_translate("call_api_decrypt_2", "Caesar Cipher"))
        self.label.setText(_translate("call_api_decrypt_2", "CEASAR CIPHER"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    call_api_decrypt_2 = QtWidgets.QMainWindow()
    ui = Ui_call_api_decrypt_2()
    ui.setupUi(call_api_decrypt_2)
    call_api_decrypt_2.show()
    sys.exit(app.exec_())
